# Generated by Django 5.0.7 on 2024-07-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_producto_pedido_detallepedido_recarga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='contrasena',
        ),
    ]
